### ISSUE TITLE
Deselect when moving cursor

### ISSUE THREAD

**Issue by X-Ryl669** [angelortega/mp-5.x#11]
First, thank you for this wonderful editor, it rocks!
Typical use case to reproduce the bug (it happens on both Qt4 and ncurses, I haven't tested other drivers):
1. Open mp5, and add some text in a document
2. Select some text with `shift+right` multiple time
3. Release `shift` press `right`
In usual editors, this deselects the text. In mp5, the selection stays alive. If I press `shift+right` again, the selection resumes as if I had pressed `shift` the whole time.

**Comment by X-Ryl669** [comment]
The following change fixes this (in mp_move.mpsl):
```
sub mp_doc.move(doc, func)
/* wrapper for movement functions, with possible shift selection */
{
    if (func != NULL) {
        if (mp.shift_pressed) {
            /* shift pressed? move selecting */
            if (doc.txt.mark == NULL)
                doc->mark();

            doc->func();
            doc->mark();
        }
        else {
            doc->unmark();
            doc->func();
        }
    }

    return doc;
}
```

**Comment by angelortega** [comment]
2017-07-24 21:40 GMT+02:00 X-Ryl669 <notifications@github.com>:

> The following change fixes this (in mp_move.mpsl):
>
> sub mp_doc.move(doc, func)
> /* wrapper for movement functions, with possible shift selection */
> {
>     if (func != NULL) {
>         if (mp.shift_pressed) {
>             /* shift pressed? move selecting */
>             if (doc.txt.mark == NULL)
>                 doc->mark();
>
>             doc->func();
>             doc->mark();
>         }
>         else {
>             doc->unmark();
>             doc->func();
>         }
>     }
>
>     return doc;
> }

Hi. This patch breaks F9 + move + F9 selection mode, which is MP's
original one (though very non-standard, I accept). Given that
shift+movement still doesn't work under curses (so there is no other
way of selecting a block) and that I have a set of users that depend
of this old behaviour, so I cannot accept it.

Thanks for your help and greetings,
Angel Ortega

**Comment by X-Ryl669** [comment]
Arg... 
So without breaking F9 behavior, we have a bug for all GUI front end, since it's not standard to press the cursor key without shift and keep the selection. So, I guess a new mode should be created, like `mp.selecting_mode` and map F9 to this. So the code will read:
```
else { 
    if (!mp.selecting_mode) doc->unmark(); 
    doc->func(); 
}
``` 
Are you ok with this change ?

**Comment by X-Ryl669** [comment]
Done the code, and it works:
```
diff --git a/mp_clipboard.mpsl b/mp_clipboard.mpsl
index 363aa41..3e14c8e 100644
--- a/mp_clipboard.mpsl
+++ b/mp_clipboard.mpsl
@@ -29,7 +29,9 @@

 mp_doc.actions ~= {
     unmark:             sub (d) { d->unmark(); },
+    mark_tag:           sub (d) { d->start_selection(0); },
     mark:               sub (d) { d->mark(); },
+    mark_tag_vertical:  sub (d) { d->start_selection(1); },
     mark_vertical:      sub (d) { d->mark_vertical(); },
     copy_mark:          sub (d) { d->busy(1)->copy()->unmark()->busy(0); },
     paste_mark:         sub (d) { d->busy(1)->store_undo()->paste()->busy(0); },
@@ -79,8 +81,8 @@ mp_doc.actions ~= {

 mp_doc.keycodes ~= {
     "f8" =>         "unmark",
-    "f9" =>         "mark",
-    "ctrl-b" =>     "mark_vertical",
+    "f9" =>         "mark_tag",
+    "ctrl-b" =>     "mark_tag_vertical",
     "ctrl-c" =>     "copy_mark",
     "ctrl-v" =>     "paste_mark",
     "ctrl-x" =>     "cut_mark",
@@ -91,8 +93,10 @@ mp_doc.keycodes ~= {

 mp.actdesc ~= {
     unmark:                   LL("Unmark block"),
-    mark:                     LL("Mark beginning/end of block"),
-    mark_vertical:            LL("Mark vertical block"),
+    mark_tag:                 LL("Mark beginning/end of block"),
+    mark:                     LL("Mark selection block"),
+    mark_tag_vertical:        LL("Mark vertical block"),
+    mark_vertical:            LL("Mark vertical selection block"),
     copy_mark:                LL("Copy block"),
     paste_mark:               LL("Paste block"),
     cut_mark:                 LL("Cut block"),
@@ -110,6 +114,23 @@ sub mp_doc.unmark(doc)
 {
     /* just destroy the mark */
     doc.txt.mark = NULL;
+    doc.txt.selecting_mode = NULL;
+
+    return doc;
+}
+
+sub mp_doc.start_selection(doc, vertical)
+/* start a toggle selection mode */
+{
+    local txt = doc.txt;
+
+    /* If there is no selection yet with keys */
+    if (txt.selecting_mode == NULL) {
+        /* Make one */
+        txt.selecting_mode = { trigger: vertical };
+    }
+    doc->mark();
+    if (vertical == 1) doc.txt.mark.vertical = 1;

     return doc;
 }
diff --git a/mp_move.mpsl b/mp_move.mpsl
index 0a38eb1..c88ba99 100644
--- a/mp_move.mpsl
+++ b/mp_move.mpsl
@@ -198,7 +198,7 @@ sub mp_doc.move(doc, func)
             doc->mark();
         }
         else {
-           doc->unmark();
+            if (doc.txt.selecting_mode == NULL) doc->unmark();
             doc->func();
         }
     }
```

**Comment by X-Ryl669** [comment]
Done in master branch. Many thanks!
