### ISSUE TITLE
Ncurses detection fails on recent distro

### ISSUE THREAD

**Issue by X-Ryl669** [angelortega/mp-5.x#14]
Recent linux distribution don't split ncurses and ncursesw like debian used to do. 
I think of Archlinux for example, but any distribution that does not install narrow char ncurses uses /usr/include/ncurses (and not /usr/include/ncursesw as in debian).
Thus, this requires changing config.sh and mpv_ncurses.c to fix the include path.

This [patch](https://github.com/X-Ryl669/mp-5.x/pull/1) fixes this by first checking if it's an old distribution else it fallbacks to the "official" include path. I'm doing it in this order since if you have a very very old system where both (narrow char) ncurses and ncursesw are installed, the opposite order would select the narrow ncurses code.

**Comment by angelortega** [comment]
2017-07-31 14:08 GMT+02:00 X-Ryl669 <notifications@github.com>:
>
> Recent linux distribution don't split ncurses and ncursesw like debian used to do.
> I think of Archlinux for example, but any distribution that does not install narrow char ncurses uses /usr/include/ncurses (and not /usr/include/ncursesw as in debian).
> Thus, this requires changing config.sh and mpv_ncurses.c to fix the include path.
>
> This patch fixes this by first checking if it's an old distribution else it fallbacks to the "official" include path. I'm doing it in this order since if you have a very very old system where both (old) ncurses and ncursesw are installed, the opposite order would select the very old ncurses code.

Hi. I've tested this patch and it fails on Debian jessie. I've fixed
it by added another -I argument with /usr/include/ncursesw in
config.sh.

diff --git a/config.sh b/config.sh
index 92a971e..6ebecd8 100755
--- a/config.sh
+++ b/config.sh
@@ -239,7 +239,7 @@ else
     echo "#include <ncursesw/ncurses.h>" > .tmp.c
     echo "int main(void) { initscr(); endwin(); return 0; }" >> .tmp.c

-    TMP_CFLAGS="-I/usr/local/include -I/usr/include/ncurses"
+    TMP_CFLAGS="-I/usr/local/include -I/usr/include/ncurses
-I/usr/include/ncursesw"
     TMP_LDFLAGS="-L/usr/local/lib -lncursesw"

     $CC $TMP_CFLAGS .tmp.c $TMP_LDFLAGS -o .tmp.o 2>> .config.log

Thank you very much for your help.

Regards,
Angel Ortega

**Comment by X-Ryl669** [comment]
This does not make sense. The code includes `ncursesw/ncurses.h` so the root of this path is `/usr/include` which is one of the default include search paths of gcc.
Adding `/usr/include/ncursesw` to the inclusion path list makes senses only if you had `#include <ncurses.h>` in the code, but it's not the case.
It should not be the case since you already have `/usr/include/ncurses` just before the second include path with `ncursesw`, so the former would get selected with a simple include `ncurses.h` directive without path => This is exactly what we want to avoid.

As I understand it, the line should be read instead:
`TMP_CFLAGS="-I/usr/local/include"`
So a user installing ncurses without her distribution package (typically in `/usr/local`) would get found too.

I've tested this change in Debian Jessie amd64 and it runs fine:
```
~/mp-5.x$ ./config.sh
Configuring...
Testing if C compiler supports -g -Wall... OK
Looking for MPDM... OK (./mpdm)
Looking for MPSL... OK (./mpsl)
Testing for win32... No
Testing for ncursesw... OK (ncursesw)
Testing for transparency support in curses... OK
Testing for wget_wch()... OK
Testing for KDE4... Disabled
Testing for Qt4... Package QtGui was not found in the pkg-config search path.
Perhaps you should add the directory containing `QtGui.pc'
to the PKG_CONFIG_PATH environment variable
No package 'QtGui' found
Package QtGui was not found in the pkg-config search path.
Perhaps you should add the directory containing `QtGui.pc'
to the PKG_CONFIG_PATH environment variable
No package 'QtGui' found
No
Testing for GTK... No
Testing for msgfmt... OK

Configured drivers: ncursesw

Type 'make' to build Minimum Profit.
```

**Comment by X-Ryl669** [comment]
If ok, please merge PR#17, it contains the fix that should work.
