### ISSUE TITLE
[Feature request] Paste in the prompt too

### ISSUE THREAD

**Issue by X-Ryl669** [angelortega/mp-5.x#22]
Currently, when in a prompt, I can't use the `Ctrl+V` shortcut to paste the clipboard content.
The pull request #21 fixes it.

**Comment by angelortega** [comment]
I've added this patch to main tree.

Thank you very much,
Angel

2017-08-04 17:54 GMT+02:00 X-Ryl669 <notifications@github.com>:

**Comment by X-Ryl669** [comment]
Thanks. Closed.
