### ISSUE TITLE
config.auto_indent breaks file & command insertion

### ISSUE THREAD

**Issue by X-Ryl669** [angelortega/mp-5.x#29]
If you set `mp.config.auto_indent = 1`, then do a `git status` via the menu, all lines will be shifted by the indentation and indentation increase each line, leading to ... strange ... output.
The same apply for `make` and so on.  

The PR #28 fixes this, by adding the `mp_doc.append` method that's bypassing indentation rules (and I suppose is faster since it does not have to deal with breaking lines and such)
I've changed the code in `mp_file` and `mp_build` and `mp_vcs` to reflect the change.

**Comment by angelortega** [comment]
2017-08-10 21:35 GMT+02:00 X-Ryl669 <notifications@github.com>:

> If you set mp.config.auto_indent = 1, then do a git status via the menu, all lines will be shifted by the indentation and indentation increase each line, leading to ... strange ... output.
> The same apply for make and so on.
>
> The PR #28 fixes this, by adding the mp_doc.append method that's bypassing indentation rules (and I suppose is faster since it does not have to deal with breaking lines and such)
> I've changed the code in mp_file and mp_build and mp_vcs to reflect the change.

I've applied this patch to the main tree.

Thanks,
Angel
