### ISSUE TITLE
how to jump to match bracket?

### ISSUE THREAD

**Issue by daogangtang** [angelortega/mp-5.x#6]
When my cursor is on one bracket, how do I do to  jump to match bracket?

**Comment by X-Ryl669** [comment]
Please see #24 for an implementation of this feature.
It's mapped to `Ctrl+J` shortcut.
@angelortega Is there an `indexOf` method for the string type I've missed ? Right now, I'm using the MPSL `for` loop for character searching, so I guess it's very inefficient.

**Comment by X-Ryl669** [comment]
Included in main repository, you can close this issue.
